// extensions/DomExample/SeriesAccessory.tsx
import '@watching/clips/elements';
import {extension} from '@watching/clips';

import {render} from 'solid-js/web';

export default extension((root) => {
  render(() => <SeasonRankings />, root);
});

import {createSignal} from 'solid-js';

export function SeasonRankings() {
  const [count, setCount] = createSignal(0);

  return (
    <ui-block-stack spacing="small">
      <ui-text>
        Season rankings!!! (rendered at {new Date().toLocaleTimeString()})
      </ui-text>
      <ui-action
        prop:onPress={() => {
          setCount(count() + 1);
        }}
      >
        Click me! {count()}
      </ui-action>
      <ui-action>
        Modal
        <ui-modal slot="overlay" padding>
          {count()}
        </ui-modal>
      </ui-action>
    </ui-block-stack>
  );
}

// extensions/DomExample/SeriesAccessory.svelte
<script lang="ts">
  import {getApi} from '@watching/clips-svelte';
  import type {SeriesQueryData} from './SeriesQuery.graphql';

  const api = getApi<'series.details.accessory', SeriesQueryData>();
  const query = api.query;

  let count = 0;

  function handlePress() {
    console.log('You clicked me!');
    count += 1;
  }
</script>

<ui-block-stack spacing="small">
  <ui-text-block>
    You are rendering in the <ui-text emphasis>{api.target}</ui-text>
    extension point, on a series named
    <ui-text emphasis="strong">{$query.series.name}</ui-text>!
  </ui-text-block>

  <ui-action on:press={handlePress}>
    Click me (count: {count})
  </ui-action>

  <ui-action>
    Modal
    <ui-modal padding slot="overlay">
      Count: {count}
    </ui-modal>
  </ui-action>
</ui-block-stack>
